### ISSUE TITLE
changing postgresql_default_auth_method results in error

### ISSUE THREAD

**Issue by 121onto** [ANXS/postgresql#155]
I would like a sensible value for `postgresql_pg_hba_default`.

The defualt for this role seems to be "trust" so that any user can login to postgresql as any other postgresql user.  Isn't this insecure?  I tried changing `postgresql_default_auth_method` to "password" but ansible complains "unable to connect to database: fe_sendauth: no password supplied"

Can someone suggest a reasonable setting for `postgresql_pg_hba_default`?  Assume I have an admin user (postgres) and an app-specific user (app) with limited privileges.

Thank you.

**Comment by easyecho** [comment]
Look into peer authentication -- http://www.postgresql.org/docs/9.4/static/auth-methods.html

**Comment by 121onto** [comment]
@easyecho thanks very much for this link.  

Didn't take long to get the information I needed.  I ended up following the example [here](http://www.upfrontsystems.co.za/Members/izak/sysadman/postgresqls-confusing-authentication-configuration) and my configuration looks as follows:

```yaml
postgresql_default_auth_method: 'md5'                                                                              
postgresql_pg_hba_default:                                                                                         
  - { type: local, database: all, user: '{{ postgresql_admin_user }}', address: '', method: 'peer' }               
  - { type: local, database: all, user: all, address: '', method: 'peer' }                                         
  - { type: host,  database: all, user: all, address: '127.0.0.1/32', method: '{{ postgresql_default_auth_method }}' }                                                                                                               
  - { type: host,  database: all, user: all, address: '::1/128',      method: '{{ postgresql_default_auth_method }}' }
```

I hope the project maintainers will consider one of two changes: 1) incorporate a sensible default into the code base; 2) add a section to the README.md that provides an example that is secure.  Doing so would contribute to both accessibility and security.

**Comment by easyecho** [comment]
:+1: that follows what I did in my fork: https://github.com/easyecho/ansible-role-postgresql/commit/be1560860405af1c30deed37ca61773a715daafe

**Comment by 121onto** [comment]
That is reassuring :100: .

If anyone would like their database username to differ from their system username, here is some playbook boilerplate to get you started:

```yaml
# run the postgresql play with configuration from the comment above 
- hosts: all                                                                                                       
  gather_facts: yes                                                                                                
  become: yes                                                                                                      
  become_method: sudo     
  tasks:
    - postgresql

# add lines to the ident file
- hosts: all                                                                                                       
  gather_facts: yes                                                                                                
  become: yes                                                                                                      
  become_method: sudo                                                                                              
  vars_files:                                                                                                      
    - roles/postgresql/defaults/main.yml                                                                             
    - group_vars/all                                                                                               
    - env/development.yml                                                                                          
  tasks:                                                                                                           
    - name: Update postgresql ident file                                                                             
      lineinfile: dest={{ postgresql_conf_directory }}/pg_ident.conf                                               
                  regexp=''                                                                                        
                  insertafter=EOF                                                                                  
                  line='app {{ app_database_user }} {{ app_user }}' 
```

I store secrets in `env/development.yml` including the database user name for my app.  The other lines should be self-explanatory.
