### ISSUE TITLE
Adding hosts from facts

### ISSUE THREAD

**Issue by tholder** [ANXS/postgresql#158]
It seems like the various pg_hba variables want a pre-built dictionary, which kinda makes sense, but how do you load it with facts from the other hosts in your playbook?

I thought this might work, but alas not:

```
postgresql_pg_hba_custom:
  - { type: host,  database: {{ database_name }}, user: {{ database_user }}, address: '{{ item.ansible_eth0.ipv4.address }}/32', method: '{{ postgresql_default_auth_method }}', comment: 'Web server internal connections:' }
  with_items: groups.webserver
```

Any ideas? This seems like a common scenario.

**Comment by jesselang** [comment]
I think you're looking to do something like:

`{{ hostvars[item]['ansible_eth0']['ipv4']['address'] }}`

See https://docs.ansible.com/ansible/playbooks_variables.html#magic-variables-and-how-to-access-information-about-other-hosts for more details.

**Comment by fivethreeo** [comment]
A trick that works:

```yaml

- name: install pgpool2
  hosts: pgpool_hosts
  become: true
  vars:
    pgpool2_wd_hostname: "{{ ansible_hostname }}"
    base_pgpool2_query_nodes:      
    - kind-jaguar.maas
    - trusty-frog.maas
  pre_tasks:
  - name: collect facts
    setup:
    delegate_to: "{{ item }}"
    delegate_facts: true
    with_items: "{{ groups['pgpool_hosts'] }}"
  - name: make the facts
    set_fact:
      pgpool2_query_nodes: "{{
        pgpool2_query_nodes|default([]) +
          [{
            'hostname': item,
            'address': hostvars[item].ansible_all_ipv4_addresses|last,
            'port': 5432,
            'wd_port': 9000
          }] }}"
    with_items: "{{ base_pgpool2_query_nodes }}"
  - debug: var=pgpool2_query_nodes
  roles:
  - pgpool2

```
