### ISSUE TITLE
debian/ubuntu dev packages

### ISSUE THREAD

**Issue by JasperAlgra** [ANXS/postgresql#278]
Hi,

For installation of some other package i'm missing the postgresql-server-dev-(version) on debian. Currently adding it via the playbook but not ideal when changing postgres versions.

Probaly as simple by replacing line 5 in `dev_headers.yml` with:

```
apt: "name={{ item }} state=present update_cache=yes"
  with_items:
    - "postgresql{{ postgresql_version_terse }}-libs"
    - "postgresql{{ postgresql_version_terse }}-devel"
```

**Comment by jlozadad** [comment]
need to fix the rhel part on thr bottom too

**Comment by jlozadad** [comment]
are the packages for this on debian named the same?

**Comment by JasperAlgra** [comment]
On debian/ubuntu:
- postgresql-server-dev-9.6
- libpq-dev

I've did: 
```
- name: PostgreSQL | Extensions | Make sure the development headers are installed | Debian
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  with_items:
    - libpq-dev
    - "postgresql-server-dev-{{ postgresql_version }}"
  when: ansible_os_family == "Debian"
  notify:
    - restart postgresql
```
