### ISSUE TITLE
Missing handler in v1.10.1

### ISSUE THREAD

**Issue by mnlm** [ANXS/postgresql#361]
The `restart postgresql` handler is missing in the latest version.
Looks like it has been removed in 5f37cfd0377698e815f0753ae4b35aa3d1e0c961.
```
TASK [ANXS.postgresql : PostgreSQL | Extensions | Make sure the postgis extensions are installed | Debian] ***
changed: [test] => (item=[u'libgeos-c1v5', u'postgresql-10-postgis-2.4', u'postgresql-10-postgis-scripts'])
ERROR! The requested handler 'restart postgresql' was not found in either the main handlers list nor in the listening handlers list
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by mnlm** [comment]
It's probably just a matter of updating the tasks in _tasks/extensions_ to use the newly defined handlers instead of the old one which got deleted.

**Comment by gclough** [comment]
That's my point... I don't think the new handlers are helpful, and complicate the code for no benefit.   If we just stick with "service", it works everywhere (i think), but if we start splitting it out between service/systemd, then we have more code and logic to maintain, but for no reason.

The private fork I use works fine using "service", and I'm on CentOS v7:

```
- name: PostgreSQL | Reload PostgreSQL to implement parameter changes  | >= v9.5
  service:
    name: "{{ postgresql_service_name }}"
    state: reloaded
  when: postgresql_version | version_compare('9.5','>=')
```
