### ISSUE TITLE
error in README pass: pass

### ISSUE THREAD

**Issue by Pepan** [ANXS/postgresql#385]
```
# List of users to be created (optional)
postgresql_users:
  - name: baz
    pass: pass
    encrypted: no       # denotes if the password is already encrypted.
```

should be

```
# List of users to be created (optional)
postgresql_users:
  - name: baz
    password: pass
    encrypted: no       # denotes if the password is already encrypted.
```
