### ISSUE TITLE
[feature] use customized systemd-file (RedHat) 

### ISSUE THREAD

**Issue by harvey637** [ANXS/postgresql#425]
Hi
sometimes I use a postgresdatabase and want to give it a easy name to control it, e.g. "holiday-db".
Then I can "systemctl start|status|stop holiday-db". I dont care about the version of postgresql in the servicename.

To achive this I modified:
```
vars/RedHat.yml:
postgresql_default_service_name: "postgresql-{{ postgresql_version }}"
```
and than in
```
tasks/configure.yml:
# - make the var overrideable from playbook
- name: Define postgresql service name
  set_fact:
    postgresql_service_name: "{{ postgresql_default_service_name }}"
  when: postgresql_service_name is not defined

# - no custom serviceunit, use conf directory
- name: PostgreSQL | Ensure the systemd directory for PostgreSQL exists | RedHat
  file:
    name: "/etc/systemd/system/postgresql-{{ postgresql_version }}.service.d"
    state: directory
    mode: 0755
  when: ansible_os_family == "RedHat" and (postgresql_default_service_name == postgresql_service_name)
  notify: restart postgresql

# - no custom serviceunit, use conf directory and default config as serviceunit
- name: PostgreSQL | Use the conf directory when starting the Postgres service | RedHat
  template:
    src: etc_systemd_system_postgresql.service.d_custom.conf.j2
    dest: "/etc/systemd/system/postgresql-{{ postgresql_version }}.service.d/custom.conf"
  when: ansible_os_family == "RedHat" and (postgresql_default_service_name == postgresql_service_name)
  register: postgresql_systemd_custom_conf

# - custom serviceunit name
- name: "Systemd unit file for {{ postgresql_service_name }}"
  copy:
    dest: /etc/systemd/system/{{ postgresql_service_name }}.service
    mode: 0644
    content: |
      # by ansible
      # create different PGDATA with a different service:
      .include /lib/systemd/system/postgresql-{{ postgresql_version }}.service
      [Service]
      User={{ postgresql_service_user }}
      Group={{ postgresql_service_group }}

      Environment=PGDATA={{ postgresql_conf_directory }}
      ExecStartPre=
      {% if postgresql_version is version_compare('10', '>=') %}
      ExecStartPre={{ postgresql_bin_directory }}/postgresql-{{ postgresql_version_terse }}-check-db-dir {{ postgresql_data_directory }}
      {% else %}
      ExecStartPre={{ postgresql_bin_directory }}/postgresql{{ postgresql_version_terse }}-check-db-dir {{ postgresql_data_directory }}
      {% endif %}

  when: ansible_os_family == "RedHat" and (postgresql_default_service_name != postgresql_service_name)
  register: postgresql_systemd_custom_conf
```
Than I can override the var _postgresql_service_name_ and create my custom serviceunit for this.

In the end I have either two tasks creating custom_conf directory and file OR my own serviceunit.
I could also use a template for my own serviceunit.
cu
Harvey

**Comment by harvey637** [comment]
also please fix the daemon-reload and the enabling of the service:
```
  - name: restart postgresql
    service:
      name: "{{ postgresql_service_name }}"
      state: restarted
      daemon_reload: yes
      enabled: "{{ postgresql_service_enabled }}"

```
