### ISSUE TITLE
error installing PG 11 on  Fedora 30 

### ISSUE THREAD

**Issue by vladp** [ANXS/postgresql#434]
Cannot figure out what I am doing wrong,
appreciate, in advance, any help/pointers.

Setup:

target host  Running Fedora 30 (within Vagrant: config.vm.box = "fedora/30-cloud-base" )
ANXS from git repo (not from galaxy)
ansible 2.7
python is python3
not using mitogen 

I checked the roles, code and in configure.yml it sets the become_user to
postgres_service_user , which is itself set to postgres_admin_user..

that seems to be correct.
I do not know how to debug if become is indeed executed.
But the code for ansible_os_family=="Redhat" seems to be doing the right thing.

```
fatal: [pg2nd__atlanta__dbhost]: FAILED! => {"changed": true, "cmd": ["/usr/pgsql-11/bin/initdb", "-D", "/var/lib/pgsq
l/11/main", "--locale=en_US.UTF-8", "--encoding=UTF-8"], "delta": "0:00:00.086695", "end": "2019-05-19 00:09:05.976242", "msg": "non-zero return code", "rc": 1, "start": "2019-05-19 00:09:05.889547", "stderr": "initdb: cannot be run as root\nPlease log in (using, e.g., \"su\") as the (unprivileged) user that will\nown the server process.", "stderr_lines": ["initdb: cannot be run as root"
, "Please log in (using, e.g., \"su\") as the (unprivileged) user that will", "own the server process."], "stdout": "", "stdout_lines": []}

```

Role parameters
   ```

---
# pg database servers
- hosts: pg_db
  become: yes
  roles:
      - role: ANXS.postgresql
        no_log: False  # added to get  better output, can be removed

        postgresql_version: 11
        postgresql_encoding: "UTF-8"
        postgresql_locale: "en_US.UTF-8"
        postgresql_ctype: "en_US.UTF-8"

        postgresql_admin_user: "postgres"
        postgresql_default_auth_method: "peer"
        postgresql_pg_hba_default:
           # .. deleted for brevity
        # end of hba stuff


        #start user
        postgresql_users:
          - name: x
            pass: x
            encrypted: no       # denotes if the password is already encrypted.

        postgresql_user_privileges:
          - name: x             # user name
            db: mydb_common             # database
            priv: "ALL"                 # privilege string format: example: INSERT,UPDATE/table:SELECT/anothertable:ALL
            role_attr_flags: "CREATEDB" # role attribute flags
        #end user
      postgresql_service_enabled: true # should the service be enabled, default is true

        postgresql_ext_install_contrib: yes
        postgresql_cluster_name: "main"
        postgresql_cluster_reset: false

        postgresql_port: "{{pgsrv_port}}"  # custom host var that  knows the expected port for pg
        postgresql_listen_addresses: "*"
        postgresql_databases:
          - name: mydb_common
       postgresql_database_extentions:
          - db: mydb_common
            extensions:
              - ltree
              - uuid-ossp
              - pgcrypto 
              - intarray 

        # List of schemas to be created (optional)
        postgresql_schemas:
          - database: mydb_common        # database name
            schema: mydbschema_public               # schema name
            owner: x
            state: present

```
