### ISSUE TITLE
Failing at the check users step

### ISSUE THREAD

**Issue by maxpearl** [ANXS/postgresql#458]
I've got a very simple test setup, and I'm getting this error:

> TASK [ANXS.postgresql : PostgreSQL | Make sure the PostgreSQL users are present] ***
fatal: [default]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}

This is on a vagrant debian stretch virtualbox

The user and database in vars don't get created.

Here's the playbook:
```
---
- hosts: all
  remote_user: root
  become: yes
  vars_files:
  - ./vars.yml
  roles:
  - { role: ANXS.postgresql, no_log: False }
```
And here are the vars:
```
postgresql_version: 9.6
postgresql_port: 5432

postgresql_databases:
  - name: testing
    owner: test

postgresql_users:
  - name: test
```

**Comment by maxpearl** [comment]
Also tried with postgresql 11, same error.

**Comment by mike1o1** [comment]
My guess is that you need to have the pip package `psycopg2` installed to be able to create users, as documented [here](https://docs.ansible.com/ansible/latest/modules/postgresql_user_module.html). I did this through a pre_task:

```yaml
- hosts: db
  become: yes
  
  pre_tasks:
    - name: Install psycopg2 for ansible to be able to create postgresql users
      pip: name=psycopg2-binary
      become: yes
      
  roles:
    - { role: ANXS.postgresql }
```

**Comment by maxpearl** [comment]
I installed psycopg2 using  Debian's python-psycopg2 package in a pre-task. So perhaps the pip installation would be preferable. But in either event (a missing psycopg2 package, or one that doesn't match what's required) should throw a more specific error, no?

**Comment by aesyondu** [comment]
> My guess is that you need to have the pip package `psycopg2` installed to be able to create users, as documented [here](https://docs.ansible.com/ansible/latest/modules/postgresql_user_module.html). I did this through a pre_task:
> 
> ```yaml
> - hosts: db
>   become: yes
>   
>   pre_tasks:
>     - name: Install psycopg2 for ansible to be able to create postgresql users
>       pip: name=psycopg2-binary
>       become: yes
>       
>   roles:
>     - { role: ANXS.postgresql }
> ```

This worked for me, I just added the install pip3 task:
```yaml
  pre_tasks:
    - name: install pip3
      become: yes
      apt: name=python3-pip state=present update_cache=true
    - name: Install psycopg2 for ansible to be able to create postgresql users
      become: yes
      pip: name=psycopg2-binary
```
