### ISSUE TITLE
Buster not Stretch

### ISSUE THREAD

**Issue by MalteKiefer** [ANXS/postgresql#487]
Hi,

I use these vars:

```yml
postgresql_version: 12
postgresql_encoding: "UTF-8"
postgresql_listen_addresses: "*"
postgresql_max_connections: 300
postgresql_wal_level: "hot_standby"
postgresql_hot_standby: "on"
postgresql_statement_timeout: 60000
postgresql_log_lock_waits: "on"
postgresql_log_destination: "csvlog"
postgresql_log_min_duration_statement: 0
postgresql_pg_hba_custom:
  - {type: "host", database: "all", user: "all", address: "0.0.0.0/0", method: "md5" }
  - {type: "host", database: "all", user: "all", address: "::/0", method: "md5" }
```

My playbook:

```yaml
- hosts: db
  remote_user: root
  vars_files:
    - ./db-custom.yml
  roles:
    - role: anxs.postgresql
  tasks:
    - name: UFW - Allow DB connections
      ufw:
        rule: allow
        port: '5432'
        proto: tcp
```
The target is a Debian server.
But when I run, I have a buster not a stretch. But I have a stretch system.
How can I change this?
