### ISSUE TITLE
Add short info whete the variables should be set

### ISSUE THREAD

**Issue by orian** [ANXS/postgresql#49]
The README specifies some example variables but it doesn't mention where should they be set (which file should be modified). I guess changing yaml in vars subdirectory is not a good idea.

It's probably worth to mention:
http://docs.ansible.com/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

Also one has to set sudo to true.

Example playbook:

```
- hosts: all
  vars_files:
      - vars.yaml
  roles:
      - setup
      - { role: postgresql, sudo: yes }
      - deploy
```
