### ISSUE TITLE
Debian Buster: no_log

### ISSUE THREAD

**Issue by mikysal78** [ANXS/postgresql#495]
Maybe repository on galaxy is not sync with github.
I download repo from github and I have add in my playbook this line:
```yml
- hosts: pgsql
  become: "{{ become | default('yes') }}"
  roles:
    - postgresql
  vars:
    # postgresql
    postgresql_version: 12
    postgresql_ext_install_postgis: yes
    postgresql_ext_install_contrib: yes
    postgresql_ext_postgis_deps:
      - libgeos-c1v5
      - "postgresql-{{ postgresql_version }}-postgis-{{ postgresql_ext_postgis_version }}"
      - "postgresql-{{ postgresql_version }}-postgis-2.5-scripts"
    postgresql_database_extensions:
      - db: openwisp2
        extensions: ["postgis"]
    postgresql_users:
      - name: openwisp2
        pass: XXXXX
    postgresql_databases:
      - name: openwisp2
        owner: openwisp2
    postgresql_user_privileges:
      - name: openwisp2
        db: openwisp2
        priv: "ALL"
```
**but i have this error:**
TASK [postgresql : PostgreSQL | Make sure the PostgreSQL users are present] ****************************************************************
fatal: [openwisp.basilicata.nnxx]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}

PLAY RECAP *********************************************************************************************************************************
openwisp.basilicata.nnxx   : ok=23   changed=0    unreachable=0    failed=1    skipped=39   rescued=0    ignored=0

**Comment by mikysal78** [comment]
it's ok with locales.
My Playbook is:
```yml
- hosts: pgsql
  become: "{{ become | default('yes') }}"
  roles:
    - postgresql
  vars:
    # postgresql
    postgresql_version: 12
    postgresql_encoding: "UTF-8"
    postgresql_locale: "it_IT.UTF-8"
    postgresql_ctype: "it_IT.UTF-8"
    postgresql_ext_install_postgis: yes
    postgresql_ext_install_contrib: yes
    postgresql_ext_postgis_deps:
      - libgeos-c1v5
      - "postgresql-{{ postgresql_version }}-postgis-{{ postgresql_ext_postgis_version }}"
      - "postgresql-{{ postgresql_version }}-postgis-2.5-scripts"
    postgresql_database_extensions:
      - db: openwisp2
        extensions: ["postgis"]
    postgresql_users:
      - name: openwisp2
        pass: XXXXX
    postgresql_databases:
      - name: openwisp2
        owner: openwisp2
    postgresql_user_privileges:
      - name: openwisp2
        db: openwisp2
        priv: "ALL"
```
