### ISSUE TITLE
Fatal error postgresql_env

### ISSUE THREAD

**Issue by storeman** [ANXS/postgresql#88]
When running the postgresql role with only some modified postgresql.conf vars, I get the following error:

```
fatal: [db1]: FAILED! => {"msg": "ERROR! the field 'environment' has an invalid value (postgresql_env), and could not be converted to an dict. Error was: ", "failed": true}
```

I cannot really solve this.

**Comment by soupdiver** [comment]
Which fields you changed and what do you have for `postgresql_locale` variable?

**Comment by storeman** [comment]
Some fields for memory usage, really, only some postgresql.conf params. The `postgresql_locale` is unchanged. When I replaced postgresql_env with the content of it:

```
- name: PostgreSQL | Install PostgreSQL
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  environment:
    LC_ALL: "{{ postgresql_locale }}"
    LC_LCTYPE: "{{ postgresql_locale }}"
    RUNLEVEL: 1
  with_items:
```

It works just fine.
    - "postgresql-{{postgresql_version}}"
    - "postgresql-client-{{postgresql_version}}"
    - "postgresql-contrib-{{postgresql_version}}"
