### ISSUE TITLE
Define owner on database

### ISSUE THREAD

**Issue by storeman** [ANXS/postgresql#90]
In `tasks/databases.yml`:

```
- name: PostgreSQL | Make sure the PostgreSQL databases are present
  postgresql_db:
    name: "{{item.name}}"
    owner: "{{item.owner | default(postgresql_database_owner)}}"
```

This last line helps me define the owner on a specific database:

```
  - name: gws2
    owner: gws2
    cube: yes
    earthdistance: yes
    tablefunc: yes
```

Tested it, and works fine!
