### ISSUE TITLE
[Question] How to use the tags?

### ISSUE THREAD

**Issue by hrstoyanov** [ANXS/postgresql#94]
If I understand the Ansible tags in roles correctly, when I use this role like this:
```
- name: Build stock Docker Postgres image, without any configuration
  hosts: localhost
  roles:
     - {role: ANXS.postgresql, tags: [postgresql-install,postgresql-extensions]}
```
I should only see the tasks tagged with **postgresql-install** and **postgresql-extensions** executed?
However, I also  see the configuration task, tagged with **postgresql-configure** also being executed, according to the playbook logs, which is something __I did not expect__!

What am I doing wrong/misunderstanding with the Ansible tags? __How can I control which tasks to execute from this role?__

Thanks,
Hristo
